### ISSUE TITLE
What is Medley Interlisp? The "About" section

### ISSUE THREAD

**Issue by masinter** [Interlisp/Interlisp.github.io#28]
The current introduction is (I think) incorrect. I was hoping to borrow the SPN intro, but that lacks substance. I find myself writing it over and over. I thought I'd open this as a discussion to develop some objectives for the introductory paragraph.

People to address
* Non-CS historians
* CS historians who don't know IDEs
* current Lisp programmers
* people who knew us way back 

Some things we might include:

* It's a historical artifact but our goal is not to preserve all the warts and misfits that come with adapting to modern expectations. So we may have some old snapshots to show, but we're also modernizing when that makes sense. There is some controversies perhaps of how much that makes sense, but we're mainly preserving things the "old way" as well.
* it was under continuous development from 69 until development tailed off in the early 90's until it was picked up 20  years later.
* Deveopment happened at PARC, XSIS, XAIS, Envos, Venue.
* It wasn't the first development environment with a GUI -- Smalltalk was. 
* It was the first workstation most users had. We had to begin demos explaining what a mouse was. 
* It won the software system award in 93 after development had pretty much evaporated.
* we're having to learn or relearn
* We're dealing with modern tools like git and github and docker and linux and modern C and Unicode.
* The common lisp implementation is old and needs bringing up to date in modern CL; the developer's tools have been updated but CL development isn't quite as smooth
* It's been called Interlisp, Interlisp-D, Xerox Lisp, Medley

# Some attempts 
I was trying to separate "About the software" "About the project accomplishments" "about the people participating" "about our goals"
------------------------

## What is Medley Interlisp?

Interlisp was a software development environment developed at Xerox PARC in the 1970s and 1980s to support research in many areas, including Artificial Intelligence, Graphical User Interfaces, and Computer-Supported Collaborative Work using HyperText. The software has many versions as it evolved since more than 50 years ago.

## What are we trying to accomplish?

Software development in Interlisp-D was a different experience than is common.
We hope to be able to not just demonstrate how it worked, but to revive the experimental development tools enough to share the ideas behind them. To make the software usable by current students of computer science, we need to overcome a number of problems. Tthere were a number of groundbreaking and influential tools, demonstrations, and applications developed in the system, that we can provide a framework for.  These include Rooms, Notecards, and LOOPS. 

## What have we done so far?

As with any software that evolved over a long time, there's been quite a bit of cleanup and retrofitting. Among other developments, you can now run Medley Interlisp on many OS and hardware configurations, or at https://online.interlisp.org in the cloud. See our [2021 Annual Report](https://interlisp.org/2021AnnualReport.pdf) and [Project News](https://interlisp.org/news/).

## Who is involved?

We are some of the original developers of Interlisp and Interlisp-D through the 70s and 80s, along with interested participants. We work with [Partners](https://interlisp.org/partners).

You can help! (See [Getting Involved](https://interlisp.org/about/getInvolved/) for ways to get involved,

**Comment by masinter** [comment]
I think it's pretty close to meeting objectives but I would like some confirmation

**Comment by nbriggs** [comment]
Content seems good.  A couple of formatting oddities -- I would remove the "code" look on the mention of "git" and "GitHub", and take out the "->" in the testimonials section at "this way: -> We have ended"
