### ISSUE TITLE
some missing links in new hugo version of interlisp.org

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/Interlisp.github.io#3]
Looking at the Javascript console when opening https://interlisp.org/hugo I notice:
```
[Error] Failed to load resource: the server responded with a status of 404 () (prism.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (Interlisp-D.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (prism.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (tabpane-persist.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (Interlisp-D.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (Interlisp-D.png, line 0)
```
Also, it's useful to run the W3C link checker [check it now!](https://validator.w3.org/checklink?uri=https%3A%2F%2Finterlisp.org%2Fhugo&hide_type=all&depth=&check=Check)

It does relatively well in the W3C Validator [validate it!](https://validator.w3.org/nu/?doc=https%3A%2F%2Finterlisp.org%2Fhugo%2F)

**Comment by stumbo** [comment]
GET https://interlisp.org/about/  [HTTP/2 200 OK 94ms]
GET https://code.jquery.com/jquery-3.6.0.min.js [HTTP/2 200 OK 0ms]
GET https://unpkg.com/lunr@2.3.9/lunr.min.js [HTTP/2 200 OK 0ms]
GET https://interlisp.org/about/Interlisp_Screen_huaaeac0c7112b6f704a2ccfcca07fadc6_33297_2000x600_fill_catmullrom_smart1_3.png [HTTP/2 200 OK 90ms]
GET https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js [HTTP/2 200 OK 0ms]
GET https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js [HTTP/2 200 OK 0ms]
GET https://interlisp.org/js/tabpane-persist.js [HTTP/2 200 OK 0ms]
GET https://interlisp.org/js/main.min.91798a335c881f1b6b805085ba4aa22d1dbd2b0b18d105d05189fa104ddae350.js [HTTP/2 200 OK 0ms]
GET https://fonts.gstatic.com/s/opensans/v34/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuU6F.woff2 [HTTP/2 200 OK 44ms]
GET https://interlisp.org/Resources/favicon.png [HTTP/2 200 OK 0ms]

All components are being found.  The last hold out, favicon.png ended up being a caching issue.  Performed without any 404s on the W3C link checker.

**Comment by nbriggs** [comment]
Did you try with recursion depth = 1 (or 2) -- I saw a bunch more 404s at depth 1.  The report had too many mime parts for your e-mail to accept it when I mailed the web page to you.
