### ISSUE TITLE
Mobile Friendly -- Web Wellness Report

### ISSUE THREAD

**Issue by stumbo** [Interlisp/Interlisp.github.io#38]
The Interlisp site is not mobile friendly.  Revise the site to make it more easy to use on a mobile device.

Update the site to improve navigation -- especially navigation on a mobile device.

[Web Wellness Report](https://github.com/Interlisp/Interlisp.github.io/files/9579292/screencapture-grader-tappnetwork-results-interlisporg-1-2022-09-15-14_49_13.pdf)

**Comment by masinter** [comment]
This is pretty vague. The main thing I noticed is that the table of content disappears when you change the window width to be narrow. This is a misfeature of the docsys theme I would imagine.
THe old web site handled this by putting the table of contents first if there wasn't room.

Is the docsys theme used being maintained? How hard is it to change themes and where do they come from? Were there other themes evaluated?

**Comment by stumbo** [comment]
I'll grant you the issue is vague.  I was more interested in pulling out the individual issues wrapped up in #11 into separate individual issues so we could evaluate and disposition them individually.

I took a quick look on my phone and, actually, the website was much more pleasing than I thought it would be.  The left hand side menu disappears but is available from the *hamburger* on the right hand side of the screen.  Select that, it expands it and pushes the page content below it. 

Unless there are specific actions we can identify that would better support responsive design I'm inclined to either leaving this hanging as a low priority item or close it as wontFix

**Comment by masinter** [comment]
Maybe changing what you call the 'hamburger' to a right-arrow ➡️ would help? 
Also, from each section (at the bottom) add a link ... for example, at the bottom of "What is Medley Interlisp?" I added a "More Background" link that points to the "About" section.

**Comment by nbriggs** [comment]
@masinter -- https://en.wikipedia.org/wiki/Hamburger_button

"It has been argued that while the collapsed menu button is now commonplace, its functionality is not necessarily immediately obvious when first encountered;[[13]](https://en.wikipedia.org/wiki/Hamburger_button#cite_note-bbc-H-mystery-13) in particular, older users less familiar with modern iconography may find it confusing.[[14]](https://en.wikipedia.org/wiki/Hamburger_button#cite_note-Loving_&_Hating_the_Hamburger_Icon-14)"

**Comment by stumbo** [comment]
As @nbriggs pointed out the hamburger train has left the station -- whether we like it or not, it is the de facto standard.  

I suspect you're right there are navigation improvements we can make.  Though I am by no means the expert in User Interface design.  I'd prefer to defer those issues to someone with knowledge in the area.

**Comment by masinter** [comment]
I think what I was missing (besides not knowing hamburgers) was that the material linked from the hamburger menu doesn't match the newer "Question?" sections. But this is more a content issue and the "mobile friendly" part of this (automated) analysis is bogus and think we can close this one.

**Comment by masinter** [comment]
closing as noted
