### ISSUE TITLE
Increase Number of Backlinks -- Web Wellness Report

### ISSUE THREAD

**Issue by stumbo** [Interlisp/Interlisp.github.io#40]
The Web Wellness Report flags the Interlisp site has having few inbound links.  

Being mentioned in blogs and on other sites would increase our reputation.  Search Engine Optimization is not a high priority, though getting noticed and attracting additional individuals interested in the Interlisp mission isn't a bad thing.

[Web Wellness Report](https://github.com/Interlisp/Interlisp.github.io/files/9579292/screencapture-grader-tappnetwork-results-interlisporg-1-2022-09-15-14_49_13.pdf)

**Comment by pamoroso** [comment]
My post [My encounter with Medley Interlisp](https://journal.paoloamoroso.com/my-encounter-with-medley-interlisp), which links to the Medley Interlisp project site, ended up [on the front page of Hacker News](https://news.ycombinator.com/item?id=34300806) and received 34K views so far on my blog. Now a Google search for `medley interlisp` returns that post in the first search results page, so I hope some of that link juice helps the project site.

**Comment by pamoroso** [comment]
Medley is the cover story of [issue 70](https://8bitnews.io/archive/2023-01-27/medley-interlisp-d-is-back) of the [8bitnews](https://8bitnews.io) retrocomputing newsletter, which linked to the project website.

**Comment by masinter** [comment]
let's focus on the website and making sure it's usable and clear. 
watch our 404 not found links (where things on the web site moved)
is there a reason to keep this issue open?

**Comment by stumbo** [comment]
No I think it's a good time to close it.
