### ISSUE TITLE
Update News with contents from 2022 Annual Report

### ISSUE THREAD

**Issue by stumbo** [Interlisp/Interlisp.github.io#50]

**Comment by masinter** [comment]
https://docs.google.com/document/d/1t3yY_twzKW4iXE6dDsEYrtlO9CyONPMv32278WH-3jU/edit

I'm not sure how best to integrate this info into our web site. It's good to have a "what's new" section about things that happened in a chronological way (which we can call annual Reports) but also integrate the material.
