### ISSUE TITLE
Update https://interlisp.org home page 

### ISSUE THREAD

**Issue by masinter** [Interlisp/Interlisp.github.io#6]
This issue is open so we can discuss changes to the home page wanted, still.

there's Interlisp/Interlisp.github.io#10 Branding -- the project name is Interlisp.org; the software is Medley. Interlisp without any other modifiers is just the language. Some parts of the web site need to be fixed to match. The Interlisp-D logo isn't right -- Interlisp-D is an older D-machine mainly system before Medley. A logo for Medley says "Medley", a logo for the group should say Interlisp.Org.

Issue Interlisp/Interlisp.github.io#7 on "who we are" I think the suggestion was to move it closer to the front (after we fix it).
Make "Documentation" its own section to promote it. Is there a principle to guide us about ordering sections that 

The Outline/Bootstrap library it uses may have reached a limit and some other framework might be better, but this area is a quagmire (or still was).  We're limited to static pages using GitHub Pages I think but online runs on Node.js so we could possibly use that if we need more dynamic.

For example, the bibliography could just integrate directly from Zotero. And default order by date (earliest of date-of-publication) sort and search.

@skaisler1 @stumbo

**Comment by stumbo** [comment]
@masinter Shall we close this issue?  We still have outstanding issues for branding and 'Who we are'.  The bulk of this issue revolved around the move to hugo.

**Comment by masinter** [comment]
@stumbo I'm still missing the basics of the workflow.
If there's an error on a web page or if someone wants to move sections around, where do they look for what to edit how? The README just has pointers to the Hugo and Docsys websites.

**Comment by masinter** [comment]
Remaining things we might do is covered by other issues, so I'm fine with closing this Issue as Done.
