### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by pictographer** [Interlisp/Interlisp.github.io#67]
Section heading [In Memoriam](https://interlisp.org/credits/in-memoriam/) links to a page with several names. Each name has a link symbol after it, but no link.

There are obituaries for all the people mentioned available on the web.

- [Danny Bobrow](https://www.paloaltoonline.com/obituaries/memorials/daniel-danny-g-bobrow-phd?o=4957)
- [Steve Purcell](https://www.paloaltoonline.com/obituaries/memorials/steve-purcell?o=5822)
- [John Sybalsky](http://www.sybalsky.net/)
- [Warren Teitelman](http://warrenteitelman.com/)

I didn't search extensively for the best links, but trusted Google's first couple of results, so there might be better ones.

**Comment by pamoroso** [comment]
I can submit a PR that changes the names with Wikipedia entries like this, or link to the obituary otherwise:

- [Danny Bobrow](https://en.wikipedia.org/wiki/Daniel_G._Bobrow) ([obituary](https://www.paloaltoonline.com/obituaries/memorials/daniel-danny-g-bobrow-phd?o=4957))

**Comment by pictographer** [comment]
The Wikipedia entry is a good addition. @pamoroso, I'll be happy to review the PR, if desired.

**Comment by pamoroso** [comment]
Okay thanks, I submitted PR #68 

I see the names are formatted as headings, possibly because a few paragraphs about these people may be added eventually. I left them as they are and just turned the names into links. An alternative would have been to render the names as a bullet list.

**Comment by pictographer** [comment]
Thank you, @pamoroso.
